// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Export the secret key as nsec bech32 string.
Future<String> exportNsec() =>
    RustLib.instance.api.crateApiIdentityExportNsec();

/// Export the public key as npub bech32 string.
Future<String> exportNpub() =>
    RustLib.instance.api.crateApiIdentityExportNpub();

/// Export the public key as hex string.
Future<String> exportPubkeyHex() =>
    RustLib.instance.api.crateApiIdentityExportPubkeyHex();

/// Publish a kind 0 metadata event to connected relays.
Future<void> setProfile({required ProfileData profile}) =>
    RustLib.instance.api.crateApiIdentitySetProfile(profile: profile);

/// Fetch the metadata for a given pubkey from connected relays.
Future<ProfileData> fetchProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiIdentityFetchProfile(pubkeyHex: pubkeyHex);

/// Nostr profile metadata (kind 0), FFI-friendly.
class ProfileData {
  final String? name;
  final String? displayName;
  final String? about;
  final String? picture;
  final String? nip05;
  final String? lud16;

  const ProfileData({
    this.name,
    this.displayName,
    this.about,
    this.picture,
    this.nip05,
    this.lud16,
  });

  static Future<ProfileData> default_() =>
      RustLib.instance.api.crateApiIdentityProfileDataDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      nip05.hashCode ^
      lud16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          about == other.about &&
          picture == other.picture &&
          nip05 == other.nip05 &&
          lud16 == other.lud16;
}
