// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `best_name`, `from_metadata`, `is_empty`, `to_metadata`

/// Export the secret key as nsec bech32 string.
Future<String> exportNsec() =>
    RustLib.instance.api.crateApiIdentityExportNsec();

/// Export the public key as npub bech32 string.
Future<String> exportNpub() =>
    RustLib.instance.api.crateApiIdentityExportNpub();

/// Export the public key as hex string.
Future<String> exportPubkeyHex() =>
    RustLib.instance.api.crateApiIdentityExportPubkeyHex();

/// Publish a kind 0 metadata event to connected relays.
Future<void> setProfile({required ProfileData profile}) =>
    RustLib.instance.api.crateApiIdentitySetProfile(profile: profile);

/// Fetch the metadata for a given pubkey.
///
/// - `blocking_sync = false`: return cached data immediately (may be empty).
/// - `blocking_sync = true`: query connected relays and wait up to 10 seconds.
///
/// Follows the White Noise two-step pattern: Flutter calls with false first,
/// then with true only if the result is empty.
Future<ProfileData> fetchProfile({
  required String pubkeyHex,
  required bool blockingSync,
}) => RustLib.instance.api.crateApiIdentityFetchProfile(
  pubkeyHex: pubkeyHex,
  blockingSync: blockingSync,
);

/// Fetch relay list (NIP-65 kind 10002) for a given pubkey.
/// Returns a list of relay URLs.
Future<List<String>> fetchUserRelays({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiIdentityFetchUserRelays(pubkeyHex: pubkeyHex);

/// Bootstrap a newly imported identity: connect default relays, fetch own
/// profile (kind 0) and relay list (NIP-65 kind 10002), then add user's
/// relays if found.
Future<ProfileData> bootstrapIdentity() =>
    RustLib.instance.api.crateApiIdentityBootstrapIdentity();

/// Look up a cached profile without any relay queries. Returns empty if not cached.
Future<ProfileData> getCachedProfile({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiIdentityGetCachedProfile(pubkeyHex: pubkeyHex);

/// Upload a profile photo to Blossom and update kind 0 metadata with the URL.
/// The image is uploaded unencrypted (public avatar, not MLS-encrypted).
Future<String> uploadProfilePhoto({
  required List<int> fileData,
  required String mimeType,
  required String blossomServerUrl,
}) => RustLib.instance.api.crateApiIdentityUploadProfilePhoto(
  fileData: fileData,
  mimeType: mimeType,
  blossomServerUrl: blossomServerUrl,
);

/// Nostr profile metadata (kind 0), FFI-friendly.
class ProfileData {
  final String? name;
  final String? displayName;
  final String? about;
  final String? picture;
  final String? nip05;
  final String? lud16;

  const ProfileData({
    this.name,
    this.displayName,
    this.about,
    this.picture,
    this.nip05,
    this.lud16,
  });

  static Future<ProfileData> default_() =>
      RustLib.instance.api.crateApiIdentityProfileDataDefault();

  @override
  int get hashCode =>
      name.hashCode ^
      displayName.hashCode ^
      about.hashCode ^
      picture.hashCode ^
      nip05.hashCode ^
      lud16.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProfileData &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          displayName == other.displayName &&
          about == other.about &&
          picture == other.picture &&
          nip05 == other.nip05 &&
          lud16 == other.lud16;
}
