// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'group.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Add members to an existing group. Admin-only.
///
/// `key_package_events_json`: JSON-serialized kind 443 KeyPackage events for each new member.
///
/// Returns an evolution event (commit) to publish and welcome rumors to gift-wrap.
/// IMPORTANT: Publish the evolution event FIRST, wait for relay ack, then merge_pending_commit,
/// then send welcome rumors via NIP-59 gift wrap. This prevents state forks per MIP-02.
Future<UpdateGroupResult> addMembers({
  required String mlsGroupIdHex,
  required List<String> keyPackageEventsJson,
}) => RustLib.instance.api.crateApiInviteAddMembers(
  mlsGroupIdHex: mlsGroupIdHex,
  keyPackageEventsJson: keyPackageEventsJson,
);

/// Remove members from a group. Admin-only.
///
/// `pubkeys_hex`: Hex-encoded public keys of members to remove.
Future<UpdateGroupResult> removeMembers({
  required String mlsGroupIdHex,
  required List<String> pubkeysHex,
}) => RustLib.instance.api.crateApiInviteRemoveMembers(
  mlsGroupIdHex: mlsGroupIdHex,
  pubkeysHex: pubkeysHex,
);

/// Process an incoming Welcome message (kind 444 rumor from NIP-59 gift wrap).
///
/// `wrapper_event_id_hex`: The hex-encoded event ID of the NIP-59 gift wrap event.
/// `welcome_rumor_json`: JSON-serialized UnsignedEvent (the unwrapped rumor).
///
/// Returns info about the group invitation for the user to accept or decline.
Future<WelcomeInfo> processWelcome({
  required String wrapperEventIdHex,
  required String welcomeRumorJson,
}) => RustLib.instance.api.crateApiInviteProcessWelcome(
  wrapperEventIdHex: wrapperEventIdHex,
  welcomeRumorJson: welcomeRumorJson,
);

/// Accept a pending welcome invitation and join the group.
Future<void> acceptWelcome({required String welcomeEventIdHex}) => RustLib
    .instance
    .api
    .crateApiInviteAcceptWelcome(welcomeEventIdHex: welcomeEventIdHex);

/// Decline a pending welcome invitation.
Future<void> declineWelcome({required String welcomeEventIdHex}) => RustLib
    .instance
    .api
    .crateApiInviteDeclineWelcome(welcomeEventIdHex: welcomeEventIdHex);

/// List pending welcome invitations.
Future<List<WelcomeInfo>> listPendingWelcomes() =>
    RustLib.instance.api.crateApiInviteListPendingWelcomes();

/// Fetch a user's KeyPackage from relays (kind 443).
///
/// Queries connected relays for the most recent KeyPackage event published by the given pubkey.
/// Returns the JSON-serialized kind 443 event, or error if not found.
Future<String> fetchKeyPackage({required String pubkeyHex}) =>
    RustLib.instance.api.crateApiInviteFetchKeyPackage(pubkeyHex: pubkeyHex);

/// Welcome information received from another user.
class WelcomeInfo {
  /// Hex-encoded welcome event ID.
  final String welcomeEventId;

  /// Hex-encoded MLS group ID.
  final String mlsGroupIdHex;

  /// Hex-encoded Nostr group ID.
  final String nostrGroupIdHex;

  /// Group name from the welcome.
  final String groupName;

  /// Group description.
  final String groupDescription;

  /// Hex-encoded public key of the person who invited us.
  final String welcomerPubkeyHex;

  /// Number of members in the group.
  final int memberCount;

  /// Welcome state: "pending", "accepted", or "declined".
  final String state;

  const WelcomeInfo({
    required this.welcomeEventId,
    required this.mlsGroupIdHex,
    required this.nostrGroupIdHex,
    required this.groupName,
    required this.groupDescription,
    required this.welcomerPubkeyHex,
    required this.memberCount,
    required this.state,
  });

  @override
  int get hashCode =>
      welcomeEventId.hashCode ^
      mlsGroupIdHex.hashCode ^
      nostrGroupIdHex.hashCode ^
      groupName.hashCode ^
      groupDescription.hashCode ^
      welcomerPubkeyHex.hashCode ^
      memberCount.hashCode ^
      state.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is WelcomeInfo &&
          runtimeType == other.runtimeType &&
          welcomeEventId == other.welcomeEventId &&
          mlsGroupIdHex == other.mlsGroupIdHex &&
          nostrGroupIdHex == other.nostrGroupIdHex &&
          groupName == other.groupName &&
          groupDescription == other.groupDescription &&
          welcomerPubkeyHex == other.welcomerPubkeyHex &&
          memberCount == other.memberCount &&
          state == other.state;
}
