// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Generate a new MLS KeyPackage for the current account.
/// Returns the data needed to create a kind 443 Nostr event.
Future<KeyPackageData> generateKeyPackage({required List<String> relayUrls}) =>
    RustLib.instance.api.crateApiKeypackageGenerateKeyPackage(
      relayUrls: relayUrls,
    );

/// Publish a KeyPackage as a kind 443 event to connected relays.
/// Signs and sends the event, returns the event ID hex.
Future<String> publishKeyPackage({required List<String> relayUrls}) => RustLib
    .instance
    .api
    .crateApiKeypackagePublishKeyPackage(relayUrls: relayUrls);

/// Publish a kind 10051 (KeyPackage relay list) event to connected relays.
/// This tells other users which relays to find our key packages on.
Future<String> publishKeyPackageRelays({required List<String> relayUrls}) =>
    RustLib.instance.api.crateApiKeypackagePublishKeyPackageRelays(
      relayUrls: relayUrls,
    );

/// A KeyPackage event ready to be published, flattened for FFI.
class KeyPackageData {
  /// Base64-encoded MLS KeyPackage bytes (content of kind 443 event).
  final String keyPackageBase64;

  /// Tags for the event as flat string pairs.
  final List<List<String>> tags;

  const KeyPackageData({required this.keyPackageBase64, required this.tags});

  @override
  int get hashCode => keyPackageBase64.hashCode ^ tags.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is KeyPackageData &&
          runtimeType == other.runtimeType &&
          keyPackageBase64 == other.keyPackageBase64 &&
          tags == other.tags;
}
