// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'meeting_intelligence.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `extract_action_items_rule_based`, `extract_decisions_rule_based`, `extract_key_points`, `extract_questions_rule_based`, `generate_basic_summary`, `generate_rule_based_notes`, `generate_title`, `intelligence`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `ActionItem`, `Decision`, `MeetingIntelligence`, `MeetingNotes`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Configure the AI backend for meeting intelligence.
Future<void> configureAiBackend({required String backendJson}) => RustLib
    .instance
    .api
    .crateApiMeetingIntelligenceConfigureAiBackend(backendJson: backendJson);

/// Generate meeting notes from a transcript.
///
/// This is the main entry point after a call ends. It processes the full
/// transcript and produces structured meeting notes.
Future<String> generateMeetingNotes({
  required String meetingId,
  required String segmentsJson,
  required String participantsJson,
  required PlatformInt64 startTimeMs,
  required PlatformInt64 endTimeMs,
}) => RustLib.instance.api.crateApiMeetingIntelligenceGenerateMeetingNotes(
  meetingId: meetingId,
  segmentsJson: segmentsJson,
  participantsJson: participantsJson,
  startTimeMs: startTimeMs,
  endTimeMs: endTimeMs,
);

/// Build a prompt for LLM-based meeting notes generation.
///
/// Used with Ollama or Claude backends.
Future<String> buildMeetingNotesPrompt({required String transcriptText}) =>
    RustLib.instance.api.crateApiMeetingIntelligenceBuildMeetingNotesPrompt(
      transcriptText: transcriptText,
    );

/// Get all archived meeting notes.
Future<String> getMeetingArchive() =>
    RustLib.instance.api.crateApiMeetingIntelligenceGetMeetingArchive();

/// Search meeting notes archive by query.
Future<String> searchMeetings({required String query}) => RustLib.instance.api
    .crateApiMeetingIntelligenceSearchMeetings(query: query);

/// Toggle action item completion status.
Future<bool> toggleActionItem({
  required String meetingId,
  required String actionItemId,
}) => RustLib.instance.api.crateApiMeetingIntelligenceToggleActionItem(
  meetingId: meetingId,
  actionItemId: actionItemId,
);

/// Get meeting notes by ID.
Future<String> getMeetingNotes({required String meetingId}) => RustLib
    .instance
    .api
    .crateApiMeetingIntelligenceGetMeetingNotes(meetingId: meetingId);

/// Export meeting notes as markdown.
Future<String> exportMeetingMarkdown({required String meetingId}) => RustLib
    .instance
    .api
    .crateApiMeetingIntelligenceExportMeetingMarkdown(meetingId: meetingId);

@freezed
sealed class AiBackend with _$AiBackend {
  const AiBackend._();

  /// Local LLM via Ollama.
  const factory AiBackend.ollama({
    required String model,
    required String endpoint,
  }) = AiBackend_Ollama;

  /// Claude API.
  const factory AiBackend.claude({
    required String apiKey,
    required String model,
  }) = AiBackend_Claude;

  /// No AI — just structural extraction (keyword-based).
  const factory AiBackend.ruleBased() = AiBackend_RuleBased;

  static Future<AiBackend> default_() =>
      RustLib.instance.api.crateApiMeetingIntelligenceAiBackendDefault();
}
