// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// A simple greeting function to verify the FFI bridge works.
String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

/// Returns the current version of the Rust core library.
String rustLibVersion() => RustLib.instance.api.crateApiSimpleRustLibVersion();
