// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `global`
// These functions are ignored because they have generic arguments: `with_state_mut`, `with_state`

/// Initialize the global state with a keypair.
Future<void> initState({required Keys keys}) =>
    RustLib.instance.api.crateApiStateInitState(keys: keys);

/// Check if state is initialized.
Future<bool> isInitialized() =>
    RustLib.instance.api.crateApiStateIsInitialized();

/// Destroy the global state (logout).
Future<void> destroyState() => RustLib.instance.api.crateApiStateDestroyState();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<BurrowState>>
abstract class BurrowState implements RustOpaqueInterface {
  Client get client;

  Keys get keys;

  MdkMdkMemoryStorage get mdk;

  set client(Client client);

  set keys(Keys keys);

  set mdk(MdkMdkMemoryStorage mdk);
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Client>>
abstract class Client implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Keys>>
abstract class Keys implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<MDK < MdkMemoryStorage >>>
abstract class MdkMdkMemoryStorage implements RustOpaqueInterface {}
