// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_data_dir`, `global`, `initialize_keyring_store`
// These functions are ignored because they have generic arguments: `with_state_mut`, `with_state`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `BurrowState`

/// Set the application data directory (called from Flutter on startup).
Future<void> setDataDir({required String path}) =>
    RustLib.instance.api.crateApiStateSetDataDir(path: path);

/// Initialize the global state with a keypair and persistent MLS storage.
Future<void> initState({required Keys keys}) =>
    RustLib.instance.api.crateApiStateInitState(keys: keys);

/// Check if state is initialized.
Future<bool> isInitialized() =>
    RustLib.instance.api.crateApiStateIsInitialized();

/// Destroy the global state (logout).
Future<void> destroyState() => RustLib.instance.api.crateApiStateDestroyState();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Keys>>
abstract class Keys implements RustOpaqueInterface {}
